# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2b026406f84ebedeb9872de85bd360898ae8e981e06c236444ea2ff60212d1fc7c03916db634f998db8681975596dc99190f0f9eb5bc3dbcbe87d28b271d0df

test:
  secret_key_base: ca8caa3288481f02ab4f8819f75826cc1a32ca4ef851b3abd1a3adcca7e463c34fa095ebdd6e1a62cca9e0eeeb0669b253679a511f92987d05696fba300a28c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
